INSERT INTO approaches (name) VALUES
('DBT'),
('CBT'),
('Attachment-based'),
('Psychodynamic'),
('Gottman Method'),
('Interpersonal'),
('Person-Centred'),
('Trauma Focused'),
('Narrative'),
('Relational'),
('ACT'),
('Mindfulness-Based'),
('Motivational Interviewing'),
('AEDP'),
('Coaching'),
('Integrative'),
('Positive Psychology'),
('Strength-Based'),
('Existential'),
('Family/Marital'),
('SFBT'),
('Jungian'),
('Psychoanalytic');