INSERT INTO doctors (first_name, last_name, title, specialisation, approach, language, session_type, age_group, participants, bio, price) VALUES
('Cambridge', 'Allen', 'Clinical Psychologist', 'Personality Disorders, Mood Disorders, Psychosis', 'Attachment-based, CBT, DBT, Family Systems, Integrative, PCIT, Play Therapy, Psychodynamic, Relational', 'Afrikaans, English', 'Online, In-person', 'Toddler, Children, Preteen, Teen, Adults', 'Individuals, Couples, Family', 'Dr. Allen brings a warm, integrative approach to complex psychological conditions. She works across the lifespan and is especially skilled in supporting families navigating personality and mood challenges.', 1200),
('Shuri', 'West', 'Counselling Psychologist', 'Grief, Depression, Relationship Issues', 'Coaching, CBT, Family/Marital, Gottman Method, Interpersonal, Person-Centred, Positive Psychology, REBT, SFBT, Trauma Focused', 'Ndebele, Northern Sotho, Sesotho, Tswana, Xhosa, Zulu', 'Online, In-person', 'Teen, Adults, Elders', 'Individuals, Family', 'Dr. West is fluent in six South African languages and brings deep cultural sensitivity to her practice. She specialises in helping clients navigate grief, depression, and relationship difficulties.', 1100),
('Okoye', 'TChalla', 'Clinical Psychologist', 'Mood Disorders, Trauma and PTSD, Personality Disorders', 'ACT, ABA, Art Therapy, CBT, DBT, Family Systems, Integrative, Narrative, Person-Centred, Psychodynamic, SFBT, Strength-Based, Trauma Focused', 'Afrikaans, English', 'Online, In-person', 'Preteen, Teen, Adults, Elders', 'Individuals, Family, Group', 'Dr. TChalla uses a creative, strength-based approach to support clients dealing with trauma, mood disorders, and personality challenges. He offers individual, family, and group therapy.', 1300),
('Nakia', 'Parker', 'Clinical Psychologist', 'Anxiety, Depression, Trauma, Grief, Relationships, Identity, Substance Use', 'Narrative, Play Therapy, Psychodynamic, Relational, Trauma Focused', 'English', 'Online, In-person', 'Children, Preteen, Teen, Adults, Elders', 'Individuals, Couples, Family', 'Dr. Parker works with a wide range of presenting concerns across all age groups. His relational, narrative approach helps clients make meaning of their experiences and build resilience.', 1150),
('Wanda', 'Mokoena', 'Clinical Psychologist', 'Anxiety, Mood Disorders, Life Transitions', 'ACT, Attachment-based, CBT, DBT, Mindfulness-Based, Motivational Interviewing, Person-Centred, SFBT, Trauma Focused', 'Afrikaans, English', 'Online, In-person', 'Adults', 'Individuals, Couples, Group', 'Dr. Mokoena specialises in supporting adults through anxiety, low mood, and major life changes. Her mindfulness-informed approach helps clients develop lasting coping strategies.', 1200),
('Madison', 'Govender', 'Clinical Psychologist', 'Trauma and PTSD', 'AEDP, Attachment-based, CBT, DBT, Family Systems, Integrative, Person-Centred, Psychodynamic, Strength-Based, Trauma Focused', 'Northern Sotho, Sesotho, Tswana, Xhosa, Zulu', 'Online, In-person', 'Teen, Adults, Elders', 'Individuals, Couples, Family', 'Dr. Govender is a trauma specialist with deep expertise in PTSD and complex trauma. He is fluent in five South African languages and known for his culturally sensitive, compassionate approach.', 1350),
('Natasha', 'Dlamini', 'Industrial Psychologist', 'Financial Psychology, Workplace Stress and Burnout, Career Guidance', 'Coaching, CBT, Gestalt, Integrative, Person-Centred, Psychodynamic, Trauma Focused', 'Ndebele, Northern Sotho, Sesotho, Swati, Tsonga, Tswana, Venda, Xhosa, Zulu', 'Online, In-person', 'Teen, Adults, Elders', 'Individuals, Couples, Family', 'Dr. Dlamini is the workplace and career specialist at Serenity. She helps clients navigate burnout, financial stress, and career transitions. She speaks nine South African languages.', 1400),
('Peter', 'Mercer', 'Clinical Psychologist', 'Anxiety, Sleep and Insomnia, Mood Disorders', 'CBT, DBT, Psychodynamic', 'Xhosa, Zulu', 'Online, In-person', 'Teen, Adults, Elders', 'Individuals', 'Dr. Mercer takes a focused, evidence-based approach to anxiety, sleep difficulties, and mood disorders. Her work is grounded in CBT and DBT with particular expertise in sleep-related conditions.', 1100),
('Tony', 'Livingston', 'Clinical Psychologist', 'Life Transitions, Grief, Coping Skills', 'CBT, Eclectic, Integrative, Mindfulness-Based, Narrative, Person-Centred, Positive Psychology', 'Sesotho, Zulu', 'Online, In-person', 'Adults', 'Individuals', 'Dr. Livingston supports adults navigating significant life changes, loss, and the development of resilient coping skills. Her positive, person-centred approach creates a safe space for growth.', 1050),
('Bruce', 'Maryland', 'Clinical Psychologist', 'Anxiety, Depression, Workplace Issues', 'Attachment-based, Coaching, Existential, Integrative, Narrative, Neuropsychology, Person-Centred, Positive Psychology, SFBT, Strength-Based', 'English', 'Online only', 'Adults, Elders', 'Individuals, Couples', 'Dr. Maryland offers online therapy for adults dealing with anxiety, depression, and workplace stress. His neuropsychology background gives him a unique perspective on how the mind and environment interact.', 1000),
('Ayo', 'Stark', 'Counselling Psychologist', 'Trauma and PTSD, Narcissistic Abuse Recovery, Career Guidance', 'ACT, Christian Counselling, Compassion Focused, DBT, Existential, Mindfulness-Based, Motivational Interviewing, Person-Centred, Positive Psychology, SFBT, Strength-Based, Trauma Focused', 'English', 'Online, In-person', 'Adults', 'Individuals, Group', 'Dr. Zhang integrates faith-sensitive and evidence-based approaches to support survivors of trauma and narcissistic abuse. She also offers career guidance for adults navigating professional transitions.', 1100),
('Fury', 'Khang', 'Clinical Psychologist', 'Relationship Issues, Family Conflict', 'CBT, Family/Marital, Integrative, Interpersonal, REBT, Relational, SFBT, Trauma Focused', 'English', 'Online, In-person', 'Adults, Elders', 'Individuals, Couples', 'Dr. Khang specialises in relationship and family dynamics. She helps couples and individuals navigate conflict, improve communication, and rebuild connection.', 1200),
('Ramonda', 'Obiagu', 'Clinical Psychologist', 'Depression, Anxiety, Emotional Disturbance', 'Family/Marital, Jungian, Psychoanalytic, Psychodynamic, SFBT, Trauma Focused', 'English', 'Online, In-person', 'Adults', 'Individuals, Couples, Groups', 'Dr. Obiagu draws on psychoanalytic and Jungian traditions to help clients explore the deeper roots of depression, anxiety, and emotional disturbance.', 1250);